local errors = require("shodan.errors")

describe("shodan.errors", function()

    describe("ShodanError", function()
        it("creates with message", function()
            local err = errors.ShodanError.new("test error")
            assert.are.equal("test error", err.message)
            assert.is_nil(err.code)
        end)

        it("creates with code", function()
            local err = errors.ShodanError.new("fail", 500)
            assert.are.equal(500, err.code)
            assert.truthy(tostring(err):find("500"))
        end)

        it("has default message", function()
            local err = errors.ShodanError.new()
            assert.are.equal("Unknown Shodan error", err.message)
        end)
    end)

    describe("APIError", function()
        it("inherits from ShodanError", function()
            local err = errors.APIError.new("api fail", 400)
            assert.is_true(errors.is_shodan_error(err))
            assert.are.equal(400, err.code)
        end)
    end)

    describe("AuthError", function()
        it("defaults to 401", function()
            local err = errors.AuthError.new()
            assert.are.equal(401, err.code)
            assert.are.equal("Invalid API key", err.message)
        end)
    end)

    describe("RateLimitError", function()
        it("defaults to 429", function()
            local err = errors.RateLimitError.new()
            assert.are.equal(429, err.code)
        end)
    end)

    describe("NotFoundError", function()
        it("defaults to 404", function()
            local err = errors.NotFoundError.new()
            assert.are.equal(404, err.code)
        end)
    end)

    describe("from_response", function()
        it("creates AuthError for 401", function()
            local err = errors.from_response(401, { error = "bad key" })
            assert.are.equal("AuthError", getmetatable(err).__name)
        end)

        it("creates NotFoundError for 404", function()
            local err = errors.from_response(404, { error = "not found" })
            assert.are.equal("NotFoundError", getmetatable(err).__name)
        end)

        it("creates RateLimitError for 429", function()
            local err = errors.from_response(429, { error = "slow down" })
            assert.are.equal("RateLimitError", getmetatable(err).__name)
        end)

        it("creates APIError for 500", function()
            local err = errors.from_response(500, "internal error")
            assert.are.equal("APIError", getmetatable(err).__name)
            assert.truthy(err.message:find("Server error"))
        end)

        it("handles string body", function()
            local err = errors.from_response(400, "bad request")
            assert.are.equal("bad request", err.message)
        end)
    end)

    describe("is_shodan_error", function()
        it("returns true for all error types", function()
            assert.is_true(errors.is_shodan_error(errors.ShodanError.new("x")))
            assert.is_true(errors.is_shodan_error(errors.APIError.new("x")))
            assert.is_true(errors.is_shodan_error(errors.AuthError.new()))
            assert.is_true(errors.is_shodan_error(errors.RateLimitError.new()))
        end)

        it("returns false for non-errors", function()
            assert.is_false(errors.is_shodan_error("string"))
            assert.is_false(errors.is_shodan_error(42))
            assert.is_false(errors.is_shodan_error({}))
        end)
    end)
end)